# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Client CI

on:
  push:
    branches: [master, master-dev]
  pull_request:
    branches: [master, master-dev]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Package
        run: |
          npm install
      - name: Built
        run: |
          npm run build --if-present
      - name: Style check
        run: |
          npm run lint
      # - name: Test react
      #   run: |
      #     make test-server
